spring:
  datasource:
#    url: jdbc:h2:~/data/demo
    url: jdbc:h2:mem:test
    username: root
    password: password


  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: "12345678901234567890123456789012"
